services:
  mongo:
    image: mongo:8.0.0
    container_name: mongo
    ports:
      - "27017:27017"  # Maps host port 27017 to container port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: adminPassword
      MONGO_INITDB_DATABASE: discordBotDB
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  discord-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: discord-api
    ports:
      - "5001:5001"  # Maps host port 5001 to container port 5001
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://Admin:adminPassword@mongo:27017/discordBotDB?authSource=admin
      PORT: 5001
    restart: always

  discord-bot-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: discord-bot-app
    depends_on:
      - discord-api
    env_file:
      - .env

volumes:
  mongo-data:
    driver: local

