services:
  mongo:
    image: mongo:8.0.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: discordBotDB
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js  # Init script to set up collections/users

  discord-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: discord-api
    ports:
      - "5000:5000" 
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/discordBotDB?authSource=discordBotDB
      PORT: 5000

  discord-bot-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: discord-bot-app
    depends_on:
      - discord-api
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GPT_API_KEY: ${CHATGPT_API_KEY}
      API_BASE_URL: http://discord-api:5000/api
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/discordBotDB?authSource=discordBotDB

volumes:
  mongo-data:
    driver: local
