version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  api-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api-service
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/discordBotDB
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend

  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: discord-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_BASE_URL=http://api-service:5000
    depends_on:
      api-service:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge
